FROM envoyproxy/envoy-alpine-dev:latest 

RUN apk update && apk add py3-pip bash curl
RUN pip3 install -q Flask==2.2.3 requests==2.28.2
RUN mkdir /code
ADD ./service.py /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/start_service.sh"]

